import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const lato = localFont({
  src: [
    { path: "./fonts/Lato-Thin.ttf", weight: "100", style: "normal" },
    { path: "./fonts/Lato-Light.ttf", weight: "300", style: "normal" },
    { path: "./fonts/Lato-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/Lato-Italic.ttf", weight: "400", style: "italic" },
    { path: "./fonts/Lato-Medium.ttf", weight: "500", style: "normal" },
    { path: "./fonts/Lato-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "./fonts/Lato-Bold.ttf", weight: "700", style: "normal" },
    { path: "./fonts/Lato-ExtraBold.ttf", weight: "800", style: "normal" },
    { path: "./fonts/Lato-Black.ttf", weight: "900", style: "normal" },
  ],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} flex min-h-screen flex-col antialiased max-w-[1920px] mx-auto bg-[#5D5D5D80]`}
      >
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
